/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 170
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 83
#define ALIAS_COUNT 0
#define TOKEN_COUNT 57
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 30
#define MAX_ALIAS_SEQUENCE_LENGTH 23
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 28
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_name = 1,
  sym_comment = 2,
  anon_sym_import = 3,
  anon_sym_ns = 4,
  anon_sym_EQ = 5,
  anon_sym_LT = 6,
  anon_sym_GT = 7,
  anon_sym_DOT = 8,
  anon_sym_LPAREN = 9,
  anon_sym_RPAREN = 10,
  anon_sym_Scenario = 11,
  anon_sym_Exec = 12,
  anon_sym_LBRACE = 13,
  anon_sym_variant = 14,
  anon_sym_COLON = 15,
  anon_sym_scene = 16,
  anon_sym_inst = 17,
  anon_sym_bhv = 18,
  anon_sym_policies = 19,
  anon_sym_COMMA = 20,
  anon_sym_RBRACE = 21,
  anon_sym_impl = 22,
  anon_sym_action = 23,
  anon_sym_obs = 24,
  anon_sym_provider = 25,
  anon_sym_ros = 26,
  anon_sym_topic = 27,
  anon_sym_type = 28,
  anon_sym_simulation = 29,
  anon_sym_entity = 30,
  anon_sym_state = 31,
  anon_sym_update_DASHrate = 32,
  anon_sym_Hz = 33,
  anon_sym_policy = 34,
  anon_sym_for = 35,
  anon_sym_horizon = 36,
  anon_sym_seconds = 37,
  anon_sym_observation = 38,
  anon_sym_observes = 39,
  anon_sym_trinary = 40,
  anon_sym_linear = 41,
  anon_sym_distance = 42,
  anon_sym_between = 43,
  anon_sym_and = 44,
  anon_sym_less_DASHthan = 45,
  anon_sym_greater_DASHthan = 46,
  anon_sym_equals = 47,
  anon_sym_tolerance = 48,
  anon_sym_mm = 49,
  anon_sym_cm = 50,
  anon_sym_m = 51,
  anon_sym_py = 52,
  anon_sym_module = 53,
  anon_sym_attr = 54,
  sym_number = 55,
  sym_string = 56,
  sym_source_file = 57,
  sym_import = 58,
  sym_namespace_decl = 59,
  sym_ref = 60,
  sym_fqn = 61,
  sym__ns_header = 62,
  sym_scenario_execution = 63,
  sym_behaviour_implementation = 64,
  sym_ros_bhv_action = 65,
  sym_observation_provider = 66,
  sym_ros_topic_provider = 67,
  sym_simulation_entity_state_provider = 68,
  sym_observation_policy = 69,
  sym_horizon_seconds = 70,
  sym_observation = 71,
  sym__policy_spec = 72,
  sym_ros_trinary_topic = 73,
  sym_linear_distance_observation = 74,
  sym_distance_constraint = 75,
  sym_distance_value = 76,
  sym_length_unit = 77,
  sym_py_module_attr = 78,
  aux_sym_source_file_repeat1 = 79,
  aux_sym_fqn_repeat1 = 80,
  aux_sym_scenario_execution_repeat1 = 81,
  aux_sym_observation_policy_repeat1 = 82,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_name] = "name",
  [sym_comment] = "comment",
  [anon_sym_import] = "import",
  [anon_sym_ns] = "ns",
  [anon_sym_EQ] = "=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_Scenario] = "Scenario",
  [anon_sym_Exec] = "Exec",
  [anon_sym_LBRACE] = "{",
  [anon_sym_variant] = "variant",
  [anon_sym_COLON] = ":",
  [anon_sym_scene] = "scene",
  [anon_sym_inst] = "inst",
  [anon_sym_bhv] = "bhv",
  [anon_sym_policies] = "policies",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_impl] = "impl",
  [anon_sym_action] = "action",
  [anon_sym_obs] = "obs",
  [anon_sym_provider] = "provider",
  [anon_sym_ros] = "ros",
  [anon_sym_topic] = "topic",
  [anon_sym_type] = "type",
  [anon_sym_simulation] = "simulation",
  [anon_sym_entity] = "entity",
  [anon_sym_state] = "state",
  [anon_sym_update_DASHrate] = "update-rate",
  [anon_sym_Hz] = "Hz",
  [anon_sym_policy] = "policy",
  [anon_sym_for] = "for",
  [anon_sym_horizon] = "horizon",
  [anon_sym_seconds] = "seconds",
  [anon_sym_observation] = "observation",
  [anon_sym_observes] = "observes",
  [anon_sym_trinary] = "trinary",
  [anon_sym_linear] = "linear",
  [anon_sym_distance] = "distance",
  [anon_sym_between] = "between",
  [anon_sym_and] = "and",
  [anon_sym_less_DASHthan] = "less-than",
  [anon_sym_greater_DASHthan] = "greater-than",
  [anon_sym_equals] = "equals",
  [anon_sym_tolerance] = "tolerance",
  [anon_sym_mm] = "mm",
  [anon_sym_cm] = "cm",
  [anon_sym_m] = "m",
  [anon_sym_py] = "py",
  [anon_sym_module] = "module",
  [anon_sym_attr] = "attr",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym_import] = "import",
  [sym_namespace_decl] = "namespace_decl",
  [sym_ref] = "ref",
  [sym_fqn] = "fqn",
  [sym__ns_header] = "_ns_header",
  [sym_scenario_execution] = "scenario_execution",
  [sym_behaviour_implementation] = "behaviour_implementation",
  [sym_ros_bhv_action] = "ros_bhv_action",
  [sym_observation_provider] = "observation_provider",
  [sym_ros_topic_provider] = "ros_topic_provider",
  [sym_simulation_entity_state_provider] = "simulation_entity_state_provider",
  [sym_observation_policy] = "observation_policy",
  [sym_horizon_seconds] = "horizon_seconds",
  [sym_observation] = "observation",
  [sym__policy_spec] = "_policy_spec",
  [sym_ros_trinary_topic] = "ros_trinary_topic",
  [sym_linear_distance_observation] = "linear_distance_observation",
  [sym_distance_constraint] = "distance_constraint",
  [sym_distance_value] = "distance_value",
  [sym_length_unit] = "length_unit",
  [sym_py_module_attr] = "py_module_attr",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_fqn_repeat1] = "fqn_repeat1",
  [aux_sym_scenario_execution_repeat1] = "scenario_execution_repeat1",
  [aux_sym_observation_policy_repeat1] = "observation_policy_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_name] = sym_name,
  [sym_comment] = sym_comment,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_ns] = anon_sym_ns,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_Scenario] = anon_sym_Scenario,
  [anon_sym_Exec] = anon_sym_Exec,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_variant] = anon_sym_variant,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_scene] = anon_sym_scene,
  [anon_sym_inst] = anon_sym_inst,
  [anon_sym_bhv] = anon_sym_bhv,
  [anon_sym_policies] = anon_sym_policies,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_impl] = anon_sym_impl,
  [anon_sym_action] = anon_sym_action,
  [anon_sym_obs] = anon_sym_obs,
  [anon_sym_provider] = anon_sym_provider,
  [anon_sym_ros] = anon_sym_ros,
  [anon_sym_topic] = anon_sym_topic,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_simulation] = anon_sym_simulation,
  [anon_sym_entity] = anon_sym_entity,
  [anon_sym_state] = anon_sym_state,
  [anon_sym_update_DASHrate] = anon_sym_update_DASHrate,
  [anon_sym_Hz] = anon_sym_Hz,
  [anon_sym_policy] = anon_sym_policy,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_horizon] = anon_sym_horizon,
  [anon_sym_seconds] = anon_sym_seconds,
  [anon_sym_observation] = anon_sym_observation,
  [anon_sym_observes] = anon_sym_observes,
  [anon_sym_trinary] = anon_sym_trinary,
  [anon_sym_linear] = anon_sym_linear,
  [anon_sym_distance] = anon_sym_distance,
  [anon_sym_between] = anon_sym_between,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_less_DASHthan] = anon_sym_less_DASHthan,
  [anon_sym_greater_DASHthan] = anon_sym_greater_DASHthan,
  [anon_sym_equals] = anon_sym_equals,
  [anon_sym_tolerance] = anon_sym_tolerance,
  [anon_sym_mm] = anon_sym_mm,
  [anon_sym_cm] = anon_sym_cm,
  [anon_sym_m] = anon_sym_m,
  [anon_sym_py] = anon_sym_py,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_attr] = anon_sym_attr,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym_import] = sym_import,
  [sym_namespace_decl] = sym_namespace_decl,
  [sym_ref] = sym_ref,
  [sym_fqn] = sym_fqn,
  [sym__ns_header] = sym__ns_header,
  [sym_scenario_execution] = sym_scenario_execution,
  [sym_behaviour_implementation] = sym_behaviour_implementation,
  [sym_ros_bhv_action] = sym_ros_bhv_action,
  [sym_observation_provider] = sym_observation_provider,
  [sym_ros_topic_provider] = sym_ros_topic_provider,
  [sym_simulation_entity_state_provider] = sym_simulation_entity_state_provider,
  [sym_observation_policy] = sym_observation_policy,
  [sym_horizon_seconds] = sym_horizon_seconds,
  [sym_observation] = sym_observation,
  [sym__policy_spec] = sym__policy_spec,
  [sym_ros_trinary_topic] = sym_ros_trinary_topic,
  [sym_linear_distance_observation] = sym_linear_distance_observation,
  [sym_distance_constraint] = sym_distance_constraint,
  [sym_distance_value] = sym_distance_value,
  [sym_length_unit] = sym_length_unit,
  [sym_py_module_attr] = sym_py_module_attr,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_fqn_repeat1] = aux_sym_fqn_repeat1,
  [aux_sym_scenario_execution_repeat1] = aux_sym_scenario_execution_repeat1,
  [aux_sym_observation_policy_repeat1] = aux_sym_observation_policy_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ns] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Scenario] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Exec] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_variant] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_scene] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inst] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bhv] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_policies] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_impl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_action] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_obs] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_provider] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ros] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_topic] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_simulation] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_entity] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_state] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_update_DASHrate] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Hz] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_policy] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_horizon] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_seconds] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_observation] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_observes] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trinary] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_linear] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_distance] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_between] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_less_DASHthan] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_greater_DASHthan] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_equals] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tolerance] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mm] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cm] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_m] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_py] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_attr] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_namespace_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_fqn] = {
    .visible = true,
    .named = true,
  },
  [sym__ns_header] = {
    .visible = false,
    .named = true,
  },
  [sym_scenario_execution] = {
    .visible = true,
    .named = true,
  },
  [sym_behaviour_implementation] = {
    .visible = true,
    .named = true,
  },
  [sym_ros_bhv_action] = {
    .visible = true,
    .named = true,
  },
  [sym_observation_provider] = {
    .visible = true,
    .named = true,
  },
  [sym_ros_topic_provider] = {
    .visible = true,
    .named = true,
  },
  [sym_simulation_entity_state_provider] = {
    .visible = true,
    .named = true,
  },
  [sym_observation_policy] = {
    .visible = true,
    .named = true,
  },
  [sym_horizon_seconds] = {
    .visible = true,
    .named = true,
  },
  [sym_observation] = {
    .visible = true,
    .named = true,
  },
  [sym__policy_spec] = {
    .visible = false,
    .named = true,
  },
  [sym_ros_trinary_topic] = {
    .visible = true,
    .named = true,
  },
  [sym_linear_distance_observation] = {
    .visible = true,
    .named = true,
  },
  [sym_distance_constraint] = {
    .visible = true,
    .named = true,
  },
  [sym_distance_value] = {
    .visible = true,
    .named = true,
  },
  [sym_length_unit] = {
    .visible = true,
    .named = true,
  },
  [sym_py_module_attr] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fqn_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scenario_execution_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_observation_policy_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_action = 1,
  field_attr = 2,
  field_bhv_impl = 3,
  field_constraint = 4,
  field_equals = 5,
  field_fluent = 6,
  field_greater_than = 7,
  field_horizon = 8,
  field_left = 9,
  field_less_than = 10,
  field_lower = 11,
  field_module = 12,
  field_name = 13,
  field_namespace = 14,
  field_path = 15,
  field_policy = 16,
  field_provider = 17,
  field_right = 18,
  field_scene_inst = 19,
  field_spec = 20,
  field_target = 21,
  field_tolerance = 22,
  field_topic = 23,
  field_type = 24,
  field_unit = 25,
  field_update_rate = 26,
  field_upper = 27,
  field_uri = 28,
  field_value = 29,
  field_variant = 30,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_action] = "action",
  [field_attr] = "attr",
  [field_bhv_impl] = "bhv_impl",
  [field_constraint] = "constraint",
  [field_equals] = "equals",
  [field_fluent] = "fluent",
  [field_greater_than] = "greater_than",
  [field_horizon] = "horizon",
  [field_left] = "left",
  [field_less_than] = "less_than",
  [field_lower] = "lower",
  [field_module] = "module",
  [field_name] = "name",
  [field_namespace] = "namespace",
  [field_path] = "path",
  [field_policy] = "policy",
  [field_provider] = "provider",
  [field_right] = "right",
  [field_scene_inst] = "scene_inst",
  [field_spec] = "spec",
  [field_target] = "target",
  [field_tolerance] = "tolerance",
  [field_topic] = "topic",
  [field_type] = "type",
  [field_unit] = "unit",
  [field_update_rate] = "update_rate",
  [field_upper] = "upper",
  [field_uri] = "uri",
  [field_value] = "value",
  [field_variant] = "variant",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 3},
  [5] = {.index = 7, .length = 1},
  [6] = {.index = 8, .length = 1},
  [7] = {.index = 9, .length = 4},
  [8] = {.index = 13, .length = 4},
  [9] = {.index = 17, .length = 1},
  [10] = {.index = 18, .length = 1},
  [11] = {.index = 19, .length = 2},
  [12] = {.index = 21, .length = 5},
  [13] = {.index = 26, .length = 1},
  [14] = {.index = 27, .length = 5},
  [15] = {.index = 32, .length = 2},
  [16] = {.index = 34, .length = 2},
  [17] = {.index = 36, .length = 3},
  [18] = {.index = 39, .length = 3},
  [19] = {.index = 42, .length = 1},
  [20] = {.index = 43, .length = 1},
  [21] = {.index = 44, .length = 2},
  [22] = {.index = 46, .length = 2},
  [23] = {.index = 48, .length = 2},
  [24] = {.index = 50, .length = 1},
  [25] = {.index = 51, .length = 6},
  [26] = {.index = 57, .length = 2},
  [27] = {.index = 59, .length = 7},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_uri, 1},
  [1] =
    {field_name, 1},
    {field_uri, 3},
  [3] =
    {field_namespace, 3},
  [4] =
    {field_name, 3},
    {field_namespace, 2, .inherited = true},
    {field_spec, 5},
  [7] =
    {field_path, 1},
  [8] =
    {field_action, 3},
  [9] =
    {field_fluent, 5},
    {field_name, 3},
    {field_namespace, 2, .inherited = true},
    {field_spec, 7},
  [13] =
    {field_fluent, 5},
    {field_name, 3},
    {field_namespace, 2, .inherited = true},
    {field_spec, 8},
  [17] =
    {field_value, 0},
  [18] =
    {field_topic, 3},
  [19] =
    {field_topic, 3},
    {field_type, 6},
  [21] =
    {field_fluent, 5},
    {field_horizon, 8},
    {field_name, 3},
    {field_namespace, 2, .inherited = true},
    {field_spec, 10},
  [26] =
    {field_update_rate, 6},
  [27] =
    {field_fluent, 5},
    {field_horizon, 8},
    {field_name, 3},
    {field_namespace, 2, .inherited = true},
    {field_spec, 11},
  [32] =
    {field_name, 1},
    {field_provider, 5},
  [34] =
    {field_attr, 8},
    {field_module, 4},
  [36] =
    {field_constraint, 7},
    {field_left, 3},
    {field_right, 5},
  [39] =
    {field_name, 1},
    {field_provider, 5},
    {field_target, 8},
  [42] =
    {field_less_than, 2},
  [43] =
    {field_greater_than, 2},
  [44] =
    {field_unit, 1},
    {field_value, 0},
  [46] =
    {field_lower, 2},
    {field_upper, 4},
  [48] =
    {field_equals, 2},
    {field_tolerance, 5},
  [50] =
    {field_policy, 1},
  [51] =
    {field_bhv_impl, 14},
    {field_name, 3},
    {field_namespace, 2, .inherited = true},
    {field_policy, 18},
    {field_scene_inst, 11},
    {field_variant, 7},
  [57] =
    {field_policy, 0, .inherited = true},
    {field_policy, 1, .inherited = true},
  [59] =
    {field_bhv_impl, 14},
    {field_name, 3},
    {field_namespace, 2, .inherited = true},
    {field_policy, 18},
    {field_policy, 19, .inherited = true},
    {field_scene_inst, 11},
    {field_variant, 7},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 151,
  [152] = 152,
  [153] = 153,
  [154] = 154,
  [155] = 155,
  [156] = 156,
  [157] = 157,
  [158] = 158,
  [159] = 159,
  [160] = 160,
  [161] = 161,
  [162] = 162,
  [163] = 163,
  [164] = 164,
  [165] = 165,
  [166] = 166,
  [167] = 167,
  [168] = 168,
  [169] = 169,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 1,
        '\'', 2,
        '(', 19,
        ')', 20,
        ',', 23,
        '.', 18,
        '/', 6,
        ':', 22,
        '<', 15,
        '=', 14,
        '>', 16,
        '{', 21,
        '}', 24,
        '+', 5,
        '-', 5,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(20);
      if (lookahead == ',') ADVANCE(23);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '>') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(8);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'E', 1,
        'H', 2,
        'S', 3,
        'a', 4,
        'b', 5,
        'c', 6,
        'd', 7,
        'e', 8,
        'f', 9,
        'g', 10,
        'h', 11,
        'i', 12,
        'l', 13,
        'm', 14,
        'n', 15,
        'o', 16,
        'p', 17,
        'r', 18,
        's', 19,
        't', 20,
        'u', 21,
        'v', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'x') ADVANCE(23);
      END_STATE();
    case 2:
      if (lookahead == 'z') ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == 'c') ADVANCE(25);
      END_STATE();
    case 4:
      if (lookahead == 'c') ADVANCE(26);
      if (lookahead == 'n') ADVANCE(27);
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(29);
      if (lookahead == 'h') ADVANCE(30);
      END_STATE();
    case 6:
      if (lookahead == 'm') ADVANCE(31);
      END_STATE();
    case 7:
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(33);
      if (lookahead == 'q') ADVANCE(34);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 11:
      if (lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 12:
      if (lookahead == 'm') ADVANCE(38);
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(40);
      if (lookahead == 'i') ADVANCE(41);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_m);
      if (lookahead == 'm') ADVANCE(42);
      if (lookahead == 'o') ADVANCE(43);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 16:
      if (lookahead == 'b') ADVANCE(45);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(46);
      if (lookahead == 'r') ADVANCE(47);
      if (lookahead == 'y') ADVANCE(48);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(49);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(50);
      if (lookahead == 'e') ADVANCE(51);
      if (lookahead == 'i') ADVANCE(52);
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(54);
      if (lookahead == 'r') ADVANCE(55);
      if (lookahead == 'y') ADVANCE(56);
      END_STATE();
    case 21:
      if (lookahead == 'p') ADVANCE(57);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(58);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_Hz);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 27:
      if (lookahead == 'd') ADVANCE(62);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(64);
      END_STATE();
    case 30:
      if (lookahead == 'v') ADVANCE(65);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_cm);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(66);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 34:
      if (lookahead == 'u') ADVANCE(68);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(69);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(71);
      END_STATE();
    case 38:
      if (lookahead == 'p') ADVANCE(72);
      END_STATE();
    case 39:
      if (lookahead == 's') ADVANCE(73);
      END_STATE();
    case 40:
      if (lookahead == 's') ADVANCE(74);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(75);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_mm);
      END_STATE();
    case 43:
      if (lookahead == 'd') ADVANCE(76);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_ns);
      END_STATE();
    case 45:
      if (lookahead == 's') ADVANCE(77);
      END_STATE();
    case 46:
      if (lookahead == 'l') ADVANCE(78);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(79);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_py);
      END_STATE();
    case 49:
      if (lookahead == 's') ADVANCE(80);
      END_STATE();
    case 50:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 51:
      if (lookahead == 'c') ADVANCE(82);
      END_STATE();
    case 52:
      if (lookahead == 'm') ADVANCE(83);
      END_STATE();
    case 53:
      if (lookahead == 'a') ADVANCE(84);
      END_STATE();
    case 54:
      if (lookahead == 'l') ADVANCE(85);
      if (lookahead == 'p') ADVANCE(86);
      END_STATE();
    case 55:
      if (lookahead == 'i') ADVANCE(87);
      END_STATE();
    case 56:
      if (lookahead == 'p') ADVANCE(88);
      END_STATE();
    case 57:
      if (lookahead == 'd') ADVANCE(89);
      END_STATE();
    case 58:
      if (lookahead == 'r') ADVANCE(90);
      END_STATE();
    case 59:
      if (lookahead == 'c') ADVANCE(91);
      END_STATE();
    case 60:
      if (lookahead == 'n') ADVANCE(92);
      END_STATE();
    case 61:
      if (lookahead == 'i') ADVANCE(93);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 63:
      if (lookahead == 'r') ADVANCE(94);
      END_STATE();
    case 64:
      if (lookahead == 'w') ADVANCE(95);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_bhv);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(96);
      END_STATE();
    case 67:
      if (lookahead == 'i') ADVANCE(97);
      END_STATE();
    case 68:
      if (lookahead == 'a') ADVANCE(98);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 70:
      if (lookahead == 'a') ADVANCE(99);
      END_STATE();
    case 71:
      if (lookahead == 'i') ADVANCE(100);
      END_STATE();
    case 72:
      if (lookahead == 'l') ADVANCE(101);
      if (lookahead == 'o') ADVANCE(102);
      END_STATE();
    case 73:
      if (lookahead == 't') ADVANCE(103);
      END_STATE();
    case 74:
      if (lookahead == 's') ADVANCE(104);
      END_STATE();
    case 75:
      if (lookahead == 'e') ADVANCE(105);
      END_STATE();
    case 76:
      if (lookahead == 'u') ADVANCE(106);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_obs);
      if (lookahead == 'e') ADVANCE(107);
      END_STATE();
    case 78:
      if (lookahead == 'i') ADVANCE(108);
      END_STATE();
    case 79:
      if (lookahead == 'v') ADVANCE(109);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_ros);
      END_STATE();
    case 81:
      if (lookahead == 'n') ADVANCE(110);
      END_STATE();
    case 82:
      if (lookahead == 'o') ADVANCE(111);
      END_STATE();
    case 83:
      if (lookahead == 'u') ADVANCE(112);
      END_STATE();
    case 84:
      if (lookahead == 't') ADVANCE(113);
      END_STATE();
    case 85:
      if (lookahead == 'e') ADVANCE(114);
      END_STATE();
    case 86:
      if (lookahead == 'i') ADVANCE(115);
      END_STATE();
    case 87:
      if (lookahead == 'n') ADVANCE(116);
      END_STATE();
    case 88:
      if (lookahead == 'e') ADVANCE(117);
      END_STATE();
    case 89:
      if (lookahead == 'a') ADVANCE(118);
      END_STATE();
    case 90:
      if (lookahead == 'i') ADVANCE(119);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_Exec);
      END_STATE();
    case 92:
      if (lookahead == 'a') ADVANCE(120);
      END_STATE();
    case 93:
      if (lookahead == 'o') ADVANCE(121);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_attr);
      END_STATE();
    case 95:
      if (lookahead == 'e') ADVANCE(122);
      END_STATE();
    case 96:
      if (lookahead == 'a') ADVANCE(123);
      END_STATE();
    case 97:
      if (lookahead == 't') ADVANCE(124);
      END_STATE();
    case 98:
      if (lookahead == 'l') ADVANCE(125);
      END_STATE();
    case 99:
      if (lookahead == 't') ADVANCE(126);
      END_STATE();
    case 100:
      if (lookahead == 'z') ADVANCE(127);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_impl);
      END_STATE();
    case 102:
      if (lookahead == 'r') ADVANCE(128);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_inst);
      END_STATE();
    case 104:
      if (lookahead == '-') ADVANCE(129);
      END_STATE();
    case 105:
      if (lookahead == 'a') ADVANCE(130);
      END_STATE();
    case 106:
      if (lookahead == 'l') ADVANCE(131);
      END_STATE();
    case 107:
      if (lookahead == 'r') ADVANCE(132);
      END_STATE();
    case 108:
      if (lookahead == 'c') ADVANCE(133);
      END_STATE();
    case 109:
      if (lookahead == 'i') ADVANCE(134);
      END_STATE();
    case 110:
      if (lookahead == 'e') ADVANCE(135);
      END_STATE();
    case 111:
      if (lookahead == 'n') ADVANCE(136);
      END_STATE();
    case 112:
      if (lookahead == 'l') ADVANCE(137);
      END_STATE();
    case 113:
      if (lookahead == 'e') ADVANCE(138);
      END_STATE();
    case 114:
      if (lookahead == 'r') ADVANCE(139);
      END_STATE();
    case 115:
      if (lookahead == 'c') ADVANCE(140);
      END_STATE();
    case 116:
      if (lookahead == 'a') ADVANCE(141);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 118:
      if (lookahead == 't') ADVANCE(142);
      END_STATE();
    case 119:
      if (lookahead == 'a') ADVANCE(143);
      END_STATE();
    case 120:
      if (lookahead == 'r') ADVANCE(144);
      END_STATE();
    case 121:
      if (lookahead == 'n') ADVANCE(145);
      END_STATE();
    case 122:
      if (lookahead == 'e') ADVANCE(146);
      END_STATE();
    case 123:
      if (lookahead == 'n') ADVANCE(147);
      END_STATE();
    case 124:
      if (lookahead == 'y') ADVANCE(148);
      END_STATE();
    case 125:
      if (lookahead == 's') ADVANCE(149);
      END_STATE();
    case 126:
      if (lookahead == 'e') ADVANCE(150);
      END_STATE();
    case 127:
      if (lookahead == 'o') ADVANCE(151);
      END_STATE();
    case 128:
      if (lookahead == 't') ADVANCE(152);
      END_STATE();
    case 129:
      if (lookahead == 't') ADVANCE(153);
      END_STATE();
    case 130:
      if (lookahead == 'r') ADVANCE(154);
      END_STATE();
    case 131:
      if (lookahead == 'e') ADVANCE(155);
      END_STATE();
    case 132:
      if (lookahead == 'v') ADVANCE(156);
      END_STATE();
    case 133:
      if (lookahead == 'i') ADVANCE(157);
      if (lookahead == 'y') ADVANCE(158);
      END_STATE();
    case 134:
      if (lookahead == 'd') ADVANCE(159);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_scene);
      END_STATE();
    case 136:
      if (lookahead == 'd') ADVANCE(160);
      END_STATE();
    case 137:
      if (lookahead == 'a') ADVANCE(161);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_state);
      END_STATE();
    case 139:
      if (lookahead == 'a') ADVANCE(162);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(anon_sym_topic);
      END_STATE();
    case 141:
      if (lookahead == 'r') ADVANCE(163);
      END_STATE();
    case 142:
      if (lookahead == 'e') ADVANCE(164);
      END_STATE();
    case 143:
      if (lookahead == 'n') ADVANCE(165);
      END_STATE();
    case 144:
      if (lookahead == 'i') ADVANCE(166);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_action);
      END_STATE();
    case 146:
      if (lookahead == 'n') ADVANCE(167);
      END_STATE();
    case 147:
      if (lookahead == 'c') ADVANCE(168);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(anon_sym_entity);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(anon_sym_equals);
      END_STATE();
    case 150:
      if (lookahead == 'r') ADVANCE(169);
      END_STATE();
    case 151:
      if (lookahead == 'n') ADVANCE(170);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 153:
      if (lookahead == 'h') ADVANCE(171);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(anon_sym_linear);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 156:
      if (lookahead == 'a') ADVANCE(172);
      if (lookahead == 'e') ADVANCE(173);
      END_STATE();
    case 157:
      if (lookahead == 'e') ADVANCE(174);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(anon_sym_policy);
      END_STATE();
    case 159:
      if (lookahead == 'e') ADVANCE(175);
      END_STATE();
    case 160:
      if (lookahead == 's') ADVANCE(176);
      END_STATE();
    case 161:
      if (lookahead == 't') ADVANCE(177);
      END_STATE();
    case 162:
      if (lookahead == 'n') ADVANCE(178);
      END_STATE();
    case 163:
      if (lookahead == 'y') ADVANCE(179);
      END_STATE();
    case 164:
      if (lookahead == '-') ADVANCE(180);
      END_STATE();
    case 165:
      if (lookahead == 't') ADVANCE(181);
      END_STATE();
    case 166:
      if (lookahead == 'o') ADVANCE(182);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(anon_sym_between);
      END_STATE();
    case 168:
      if (lookahead == 'e') ADVANCE(183);
      END_STATE();
    case 169:
      if (lookahead == '-') ADVANCE(184);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(anon_sym_horizon);
      END_STATE();
    case 171:
      if (lookahead == 'a') ADVANCE(185);
      END_STATE();
    case 172:
      if (lookahead == 't') ADVANCE(186);
      END_STATE();
    case 173:
      if (lookahead == 's') ADVANCE(187);
      END_STATE();
    case 174:
      if (lookahead == 's') ADVANCE(188);
      END_STATE();
    case 175:
      if (lookahead == 'r') ADVANCE(189);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(anon_sym_seconds);
      END_STATE();
    case 177:
      if (lookahead == 'i') ADVANCE(190);
      END_STATE();
    case 178:
      if (lookahead == 'c') ADVANCE(191);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(anon_sym_trinary);
      END_STATE();
    case 180:
      if (lookahead == 'r') ADVANCE(192);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(anon_sym_variant);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(anon_sym_Scenario);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(anon_sym_distance);
      END_STATE();
    case 184:
      if (lookahead == 't') ADVANCE(193);
      END_STATE();
    case 185:
      if (lookahead == 'n') ADVANCE(194);
      END_STATE();
    case 186:
      if (lookahead == 'i') ADVANCE(195);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(anon_sym_observes);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(anon_sym_policies);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(anon_sym_provider);
      END_STATE();
    case 190:
      if (lookahead == 'o') ADVANCE(196);
      END_STATE();
    case 191:
      if (lookahead == 'e') ADVANCE(197);
      END_STATE();
    case 192:
      if (lookahead == 'a') ADVANCE(198);
      END_STATE();
    case 193:
      if (lookahead == 'h') ADVANCE(199);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(anon_sym_less_DASHthan);
      END_STATE();
    case 195:
      if (lookahead == 'o') ADVANCE(200);
      END_STATE();
    case 196:
      if (lookahead == 'n') ADVANCE(201);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(anon_sym_tolerance);
      END_STATE();
    case 198:
      if (lookahead == 't') ADVANCE(202);
      END_STATE();
    case 199:
      if (lookahead == 'a') ADVANCE(203);
      END_STATE();
    case 200:
      if (lookahead == 'n') ADVANCE(204);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(anon_sym_simulation);
      END_STATE();
    case 202:
      if (lookahead == 'e') ADVANCE(205);
      END_STATE();
    case 203:
      if (lookahead == 'n') ADVANCE(206);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(anon_sym_observation);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(anon_sym_update_DASHrate);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(anon_sym_greater_DASHthan);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 4},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 0},
  [156] = {.lex_state = 0},
  [157] = {.lex_state = 0},
  [158] = {.lex_state = 0},
  [159] = {.lex_state = 0},
  [160] = {.lex_state = 0},
  [161] = {.lex_state = 0},
  [162] = {.lex_state = 0},
  [163] = {.lex_state = 0},
  [164] = {.lex_state = 0},
  [165] = {.lex_state = 0},
  [166] = {.lex_state = 0},
  [167] = {.lex_state = 0},
  [168] = {.lex_state = 0},
  [169] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_ns] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_Scenario] = ACTIONS(1),
    [anon_sym_Exec] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_variant] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_scene] = ACTIONS(1),
    [anon_sym_inst] = ACTIONS(1),
    [anon_sym_bhv] = ACTIONS(1),
    [anon_sym_policies] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_impl] = ACTIONS(1),
    [anon_sym_action] = ACTIONS(1),
    [anon_sym_obs] = ACTIONS(1),
    [anon_sym_provider] = ACTIONS(1),
    [anon_sym_ros] = ACTIONS(1),
    [anon_sym_topic] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_simulation] = ACTIONS(1),
    [anon_sym_entity] = ACTIONS(1),
    [anon_sym_state] = ACTIONS(1),
    [anon_sym_update_DASHrate] = ACTIONS(1),
    [anon_sym_Hz] = ACTIONS(1),
    [anon_sym_policy] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_horizon] = ACTIONS(1),
    [anon_sym_seconds] = ACTIONS(1),
    [anon_sym_observation] = ACTIONS(1),
    [anon_sym_observes] = ACTIONS(1),
    [anon_sym_trinary] = ACTIONS(1),
    [anon_sym_linear] = ACTIONS(1),
    [anon_sym_distance] = ACTIONS(1),
    [anon_sym_between] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_less_DASHthan] = ACTIONS(1),
    [anon_sym_greater_DASHthan] = ACTIONS(1),
    [anon_sym_equals] = ACTIONS(1),
    [anon_sym_tolerance] = ACTIONS(1),
    [anon_sym_mm] = ACTIONS(1),
    [anon_sym_cm] = ACTIONS(1),
    [anon_sym_m] = ACTIONS(1),
    [anon_sym_py] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_attr] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(168),
    [sym_import] = STATE(2),
    [sym_namespace_decl] = STATE(2),
    [sym_scenario_execution] = STATE(2),
    [sym_behaviour_implementation] = STATE(2),
    [sym_observation_provider] = STATE(2),
    [sym_observation_policy] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_import] = ACTIONS(7),
    [anon_sym_ns] = ACTIONS(9),
    [anon_sym_Scenario] = ACTIONS(11),
    [anon_sym_bhv] = ACTIONS(13),
    [anon_sym_obs] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_ns,
    ACTIONS(11), 1,
      anon_sym_Scenario,
    ACTIONS(13), 1,
      anon_sym_bhv,
    ACTIONS(15), 1,
      anon_sym_obs,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(3), 7,
      sym_import,
      sym_namespace_decl,
      sym_scenario_execution,
      sym_behaviour_implementation,
      sym_observation_provider,
      sym_observation_policy,
      aux_sym_source_file_repeat1,
  [31] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_import,
    ACTIONS(24), 1,
      anon_sym_ns,
    ACTIONS(27), 1,
      anon_sym_Scenario,
    ACTIONS(30), 1,
      anon_sym_bhv,
    ACTIONS(33), 1,
      anon_sym_obs,
    STATE(3), 7,
      sym_import,
      sym_namespace_decl,
      sym_scenario_execution,
      sym_behaviour_implementation,
      sym_observation_provider,
      sym_observation_policy,
      aux_sym_source_file_repeat1,
  [62] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      anon_sym_observation,
    ACTIONS(38), 1,
      anon_sym_trinary,
    ACTIONS(40), 1,
      anon_sym_linear,
    ACTIONS(42), 1,
      anon_sym_py,
    STATE(5), 2,
      sym_observation,
      aux_sym_observation_policy_repeat1,
    STATE(167), 4,
      sym__policy_spec,
      sym_ros_trinary_topic,
      sym_linear_distance_observation,
      sym_py_module_attr,
  [88] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      anon_sym_observation,
    ACTIONS(38), 1,
      anon_sym_trinary,
    ACTIONS(40), 1,
      anon_sym_linear,
    ACTIONS(42), 1,
      anon_sym_py,
    STATE(14), 2,
      sym_observation,
      aux_sym_observation_policy_repeat1,
    STATE(82), 4,
      sym__policy_spec,
      sym_ros_trinary_topic,
      sym_linear_distance_observation,
      sym_py_module_attr,
  [114] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      anon_sym_observation,
    ACTIONS(38), 1,
      anon_sym_trinary,
    ACTIONS(40), 1,
      anon_sym_linear,
    ACTIONS(42), 1,
      anon_sym_py,
    STATE(14), 2,
      sym_observation,
      aux_sym_observation_policy_repeat1,
    STATE(112), 4,
      sym__policy_spec,
      sym_ros_trinary_topic,
      sym_linear_distance_observation,
      sym_py_module_attr,
  [140] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      anon_sym_observation,
    ACTIONS(38), 1,
      anon_sym_trinary,
    ACTIONS(40), 1,
      anon_sym_linear,
    ACTIONS(42), 1,
      anon_sym_py,
    STATE(6), 2,
      sym_observation,
      aux_sym_observation_policy_repeat1,
    STATE(103), 4,
      sym__policy_spec,
      sym_ros_trinary_topic,
      sym_linear_distance_observation,
      sym_py_module_attr,
  [166] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(44), 9,
      anon_sym_LBRACE,
      anon_sym_scene,
      anon_sym_bhv,
      anon_sym_policies,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_horizon,
      anon_sym_observes,
      anon_sym_and,
  [181] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_ns,
      anon_sym_Scenario,
      anon_sym_bhv,
      anon_sym_obs,
  [193] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_ns,
      anon_sym_Scenario,
      anon_sym_bhv,
      anon_sym_obs,
  [205] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_ns,
      anon_sym_Scenario,
      anon_sym_bhv,
      anon_sym_obs,
  [217] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_ns,
      anon_sym_Scenario,
      anon_sym_bhv,
      anon_sym_obs,
  [229] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_ns,
      anon_sym_Scenario,
      anon_sym_bhv,
      anon_sym_obs,
  [241] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_observation,
    STATE(14), 2,
      sym_observation,
      aux_sym_observation_policy_repeat1,
    ACTIONS(55), 3,
      anon_sym_trinary,
      anon_sym_linear,
      anon_sym_py,
  [257] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_ns,
      anon_sym_Scenario,
      anon_sym_bhv,
      anon_sym_obs,
  [269] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_ns,
      anon_sym_Scenario,
      anon_sym_bhv,
      anon_sym_obs,
  [281] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_ns,
      anon_sym_Scenario,
      anon_sym_bhv,
      anon_sym_obs,
  [293] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_ns,
      anon_sym_Scenario,
      anon_sym_bhv,
      anon_sym_obs,
  [305] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_ns,
      anon_sym_Scenario,
      anon_sym_bhv,
      anon_sym_obs,
  [317] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_ns,
      anon_sym_Scenario,
      anon_sym_bhv,
      anon_sym_obs,
  [329] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_ns,
      anon_sym_Scenario,
      anon_sym_bhv,
      anon_sym_obs,
  [341] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_ns,
      anon_sym_Scenario,
      anon_sym_bhv,
      anon_sym_obs,
  [353] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_ns,
      anon_sym_Scenario,
      anon_sym_bhv,
      anon_sym_obs,
  [365] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_DOT,
    STATE(25), 1,
      aux_sym_fqn_repeat1,
    ACTIONS(75), 3,
      anon_sym_GT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [380] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_DOT,
    STATE(26), 1,
      aux_sym_fqn_repeat1,
    ACTIONS(79), 3,
      anon_sym_GT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [395] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_DOT,
    STATE(26), 1,
      aux_sym_fqn_repeat1,
    ACTIONS(81), 3,
      anon_sym_GT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [410] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_between,
    ACTIONS(88), 1,
      anon_sym_less_DASHthan,
    ACTIONS(90), 1,
      anon_sym_greater_DASHthan,
    ACTIONS(92), 1,
      anon_sym_equals,
    STATE(131), 1,
      sym_distance_constraint,
  [429] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_py,
    ACTIONS(94), 1,
      anon_sym_bhv,
    STATE(72), 1,
      sym_ros_bhv_action,
    STATE(109), 1,
      sym_py_module_attr,
  [445] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 4,
      anon_sym_GT,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [455] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 4,
      anon_sym_observation,
      anon_sym_trinary,
      anon_sym_linear,
      anon_sym_py,
  [465] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 4,
      anon_sym_observation,
      anon_sym_trinary,
      anon_sym_linear,
      anon_sym_py,
  [475] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_m,
    STATE(36), 1,
      sym_length_unit,
    ACTIONS(100), 2,
      anon_sym_mm,
      anon_sym_cm,
  [489] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_LT,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      sym_ref,
  [502] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_ros,
    STATE(137), 1,
      sym_ros_topic_provider,
    STATE(146), 1,
      sym_simulation_entity_state_provider,
  [515] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 3,
      anon_sym_RBRACE,
      anon_sym_and,
      anon_sym_tolerance,
  [524] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 3,
      anon_sym_RBRACE,
      anon_sym_and,
      anon_sym_tolerance,
  [533] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    STATE(38), 1,
      aux_sym_scenario_execution_repeat1,
  [546] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_COMMA,
    ACTIONS(120), 1,
      anon_sym_RBRACE,
    STATE(40), 1,
      aux_sym_scenario_execution_repeat1,
  [559] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_LT,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      sym_ref,
  [572] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    STATE(40), 1,
      aux_sym_scenario_execution_repeat1,
  [585] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_LT,
    STATE(124), 1,
      sym_ref,
  [595] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_topic,
    ACTIONS(131), 1,
      anon_sym_simulation,
  [605] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      sym_number,
    STATE(85), 1,
      sym_horizon_seconds,
  [615] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      sym_name,
    STATE(87), 1,
      sym_fqn,
  [625] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_LT,
    STATE(102), 1,
      sym_ref,
  [635] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_LT,
    STATE(105), 1,
      sym_ref,
  [645] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_LT,
    STATE(49), 1,
      sym_ref,
  [655] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_LT,
    STATE(117), 1,
      sym_ref,
  [665] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
    ACTIONS(139), 1,
      anon_sym_observes,
  [675] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_LT,
    STATE(64), 1,
      sym_ref,
  [685] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_LT,
    STATE(133), 1,
      sym_ref,
  [695] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      sym_number,
    STATE(142), 1,
      sym_distance_value,
  [705] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      sym_number,
    STATE(143), 1,
      sym_distance_value,
  [715] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      sym_number,
    STATE(144), 1,
      sym_distance_value,
  [725] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      sym_number,
    STATE(145), 1,
      sym_distance_value,
  [735] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      sym_name,
    STATE(115), 1,
      sym_fqn,
  [745] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_LT,
    STATE(37), 1,
      sym_ref,
  [755] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      sym_name,
    STATE(141), 1,
      sym_fqn,
  [765] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_LBRACE,
    ACTIONS(145), 1,
      anon_sym_horizon,
  [775] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      sym_number,
    STATE(152), 1,
      sym_distance_value,
  [785] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_LT,
    STATE(151), 1,
      sym_ref,
  [795] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      sym_number,
    STATE(157), 1,
      sym_distance_value,
  [805] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_LPAREN,
    STATE(81), 1,
      sym__ns_header,
  [815] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [823] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_provider,
    ACTIONS(153), 1,
      anon_sym_policy,
  [833] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_LPAREN,
    STATE(83), 1,
      sym__ns_header,
  [843] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_LPAREN,
    STATE(93), 1,
      sym__ns_header,
  [853] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_LPAREN,
    STATE(95), 1,
      sym__ns_header,
  [863] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_LT,
    STATE(59), 1,
      sym_ref,
  [873] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_RBRACE,
  [880] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_ns,
  [887] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
  [894] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_inst,
  [901] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_RBRACE,
  [908] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      sym_name,
  [915] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_type,
  [922] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_update_DASHrate,
  [929] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_LBRACE,
  [936] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_COLON,
  [943] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_between,
  [950] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      sym_name,
  [957] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_RBRACE,
  [964] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      sym_name,
  [971] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_seconds,
  [978] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_LBRACE,
  [985] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_COLON,
  [992] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_COMMA,
  [999] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_COLON,
  [1006] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_COLON,
  [1013] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_provider,
  [1020] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_string,
  [1027] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      sym_string,
  [1034] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      sym_name,
  [1041] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_LBRACE,
  [1048] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym_name,
  [1055] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      sym_name,
  [1062] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_attr,
  [1069] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      sym_string,
  [1076] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      sym_number,
  [1083] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_COLON,
  [1090] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_RBRACE,
  [1097] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_and,
  [1104] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_RBRACE,
  [1111] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_impl,
  [1118] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_bhv,
  [1125] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_COLON,
  [1132] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_RBRACE,
  [1139] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_Hz,
  [1146] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_RBRACE,
  [1153] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_COLON,
  [1160] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_EQ,
  [1167] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_RBRACE,
  [1174] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_COLON,
  [1181] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_name,
  [1188] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
  [1195] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_module,
  [1202] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_LBRACE,
  [1209] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_LBRACE,
  [1216] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      sym_name,
  [1223] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      anon_sym_RBRACE,
  [1230] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_LBRACE,
  [1237] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_COLON,
  [1244] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_LBRACE,
  [1251] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_policies,
  [1258] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_RBRACE,
  [1265] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_EQ,
  [1272] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_COLON,
  [1279] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_COLON,
  [1286] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_COLON,
  [1293] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_COLON,
  [1300] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_RBRACE,
  [1307] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_COLON,
  [1314] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_RBRACE,
  [1321] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_COLON,
  [1328] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_entity,
  [1335] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_action,
  [1342] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_RBRACE,
  [1349] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      anon_sym_RBRACE,
  [1356] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_LBRACE,
  [1363] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      anon_sym_for,
  [1370] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_GT,
  [1377] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_and,
  [1384] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_RBRACE,
  [1391] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      anon_sym_RBRACE,
  [1398] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      anon_sym_tolerance,
  [1405] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_RBRACE,
  [1412] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      anon_sym_COLON,
  [1419] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_LBRACE,
  [1426] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_Exec,
  [1433] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_COLON,
  [1440] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      anon_sym_scene,
  [1447] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_RBRACE,
  [1454] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      sym_string,
  [1461] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_variant,
  [1468] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_RBRACE,
  [1475] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      anon_sym_COLON,
  [1482] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_RBRACE,
  [1489] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      anon_sym_RBRACE,
  [1496] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      sym_string,
  [1503] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      anon_sym_state,
  [1510] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      sym_string,
  [1517] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      anon_sym_RBRACE,
  [1524] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      sym_name,
  [1531] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      anon_sym_topic,
  [1538] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_RBRACE,
  [1545] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      anon_sym_distance,
  [1552] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_RBRACE,
  [1559] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      ts_builtin_sym_end,
  [1566] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 88,
  [SMALL_STATE(6)] = 114,
  [SMALL_STATE(7)] = 140,
  [SMALL_STATE(8)] = 166,
  [SMALL_STATE(9)] = 181,
  [SMALL_STATE(10)] = 193,
  [SMALL_STATE(11)] = 205,
  [SMALL_STATE(12)] = 217,
  [SMALL_STATE(13)] = 229,
  [SMALL_STATE(14)] = 241,
  [SMALL_STATE(15)] = 257,
  [SMALL_STATE(16)] = 269,
  [SMALL_STATE(17)] = 281,
  [SMALL_STATE(18)] = 293,
  [SMALL_STATE(19)] = 305,
  [SMALL_STATE(20)] = 317,
  [SMALL_STATE(21)] = 329,
  [SMALL_STATE(22)] = 341,
  [SMALL_STATE(23)] = 353,
  [SMALL_STATE(24)] = 365,
  [SMALL_STATE(25)] = 380,
  [SMALL_STATE(26)] = 395,
  [SMALL_STATE(27)] = 410,
  [SMALL_STATE(28)] = 429,
  [SMALL_STATE(29)] = 445,
  [SMALL_STATE(30)] = 455,
  [SMALL_STATE(31)] = 465,
  [SMALL_STATE(32)] = 475,
  [SMALL_STATE(33)] = 489,
  [SMALL_STATE(34)] = 502,
  [SMALL_STATE(35)] = 515,
  [SMALL_STATE(36)] = 524,
  [SMALL_STATE(37)] = 533,
  [SMALL_STATE(38)] = 546,
  [SMALL_STATE(39)] = 559,
  [SMALL_STATE(40)] = 572,
  [SMALL_STATE(41)] = 585,
  [SMALL_STATE(42)] = 595,
  [SMALL_STATE(43)] = 605,
  [SMALL_STATE(44)] = 615,
  [SMALL_STATE(45)] = 625,
  [SMALL_STATE(46)] = 635,
  [SMALL_STATE(47)] = 645,
  [SMALL_STATE(48)] = 655,
  [SMALL_STATE(49)] = 665,
  [SMALL_STATE(50)] = 675,
  [SMALL_STATE(51)] = 685,
  [SMALL_STATE(52)] = 695,
  [SMALL_STATE(53)] = 705,
  [SMALL_STATE(54)] = 715,
  [SMALL_STATE(55)] = 725,
  [SMALL_STATE(56)] = 735,
  [SMALL_STATE(57)] = 745,
  [SMALL_STATE(58)] = 755,
  [SMALL_STATE(59)] = 765,
  [SMALL_STATE(60)] = 775,
  [SMALL_STATE(61)] = 785,
  [SMALL_STATE(62)] = 795,
  [SMALL_STATE(63)] = 805,
  [SMALL_STATE(64)] = 815,
  [SMALL_STATE(65)] = 823,
  [SMALL_STATE(66)] = 833,
  [SMALL_STATE(67)] = 843,
  [SMALL_STATE(68)] = 853,
  [SMALL_STATE(69)] = 863,
  [SMALL_STATE(70)] = 873,
  [SMALL_STATE(71)] = 880,
  [SMALL_STATE(72)] = 887,
  [SMALL_STATE(73)] = 894,
  [SMALL_STATE(74)] = 901,
  [SMALL_STATE(75)] = 908,
  [SMALL_STATE(76)] = 915,
  [SMALL_STATE(77)] = 922,
  [SMALL_STATE(78)] = 929,
  [SMALL_STATE(79)] = 936,
  [SMALL_STATE(80)] = 943,
  [SMALL_STATE(81)] = 950,
  [SMALL_STATE(82)] = 957,
  [SMALL_STATE(83)] = 964,
  [SMALL_STATE(84)] = 971,
  [SMALL_STATE(85)] = 978,
  [SMALL_STATE(86)] = 985,
  [SMALL_STATE(87)] = 992,
  [SMALL_STATE(88)] = 999,
  [SMALL_STATE(89)] = 1006,
  [SMALL_STATE(90)] = 1013,
  [SMALL_STATE(91)] = 1020,
  [SMALL_STATE(92)] = 1027,
  [SMALL_STATE(93)] = 1034,
  [SMALL_STATE(94)] = 1041,
  [SMALL_STATE(95)] = 1048,
  [SMALL_STATE(96)] = 1055,
  [SMALL_STATE(97)] = 1062,
  [SMALL_STATE(98)] = 1069,
  [SMALL_STATE(99)] = 1076,
  [SMALL_STATE(100)] = 1083,
  [SMALL_STATE(101)] = 1090,
  [SMALL_STATE(102)] = 1097,
  [SMALL_STATE(103)] = 1104,
  [SMALL_STATE(104)] = 1111,
  [SMALL_STATE(105)] = 1118,
  [SMALL_STATE(106)] = 1125,
  [SMALL_STATE(107)] = 1132,
  [SMALL_STATE(108)] = 1139,
  [SMALL_STATE(109)] = 1146,
  [SMALL_STATE(110)] = 1153,
  [SMALL_STATE(111)] = 1160,
  [SMALL_STATE(112)] = 1167,
  [SMALL_STATE(113)] = 1174,
  [SMALL_STATE(114)] = 1181,
  [SMALL_STATE(115)] = 1188,
  [SMALL_STATE(116)] = 1195,
  [SMALL_STATE(117)] = 1202,
  [SMALL_STATE(118)] = 1209,
  [SMALL_STATE(119)] = 1216,
  [SMALL_STATE(120)] = 1223,
  [SMALL_STATE(121)] = 1230,
  [SMALL_STATE(122)] = 1237,
  [SMALL_STATE(123)] = 1244,
  [SMALL_STATE(124)] = 1251,
  [SMALL_STATE(125)] = 1258,
  [SMALL_STATE(126)] = 1265,
  [SMALL_STATE(127)] = 1272,
  [SMALL_STATE(128)] = 1279,
  [SMALL_STATE(129)] = 1286,
  [SMALL_STATE(130)] = 1293,
  [SMALL_STATE(131)] = 1300,
  [SMALL_STATE(132)] = 1307,
  [SMALL_STATE(133)] = 1314,
  [SMALL_STATE(134)] = 1321,
  [SMALL_STATE(135)] = 1328,
  [SMALL_STATE(136)] = 1335,
  [SMALL_STATE(137)] = 1342,
  [SMALL_STATE(138)] = 1349,
  [SMALL_STATE(139)] = 1356,
  [SMALL_STATE(140)] = 1363,
  [SMALL_STATE(141)] = 1370,
  [SMALL_STATE(142)] = 1377,
  [SMALL_STATE(143)] = 1384,
  [SMALL_STATE(144)] = 1391,
  [SMALL_STATE(145)] = 1398,
  [SMALL_STATE(146)] = 1405,
  [SMALL_STATE(147)] = 1412,
  [SMALL_STATE(148)] = 1419,
  [SMALL_STATE(149)] = 1426,
  [SMALL_STATE(150)] = 1433,
  [SMALL_STATE(151)] = 1440,
  [SMALL_STATE(152)] = 1447,
  [SMALL_STATE(153)] = 1454,
  [SMALL_STATE(154)] = 1461,
  [SMALL_STATE(155)] = 1468,
  [SMALL_STATE(156)] = 1475,
  [SMALL_STATE(157)] = 1482,
  [SMALL_STATE(158)] = 1489,
  [SMALL_STATE(159)] = 1496,
  [SMALL_STATE(160)] = 1503,
  [SMALL_STATE(161)] = 1510,
  [SMALL_STATE(162)] = 1517,
  [SMALL_STATE(163)] = 1524,
  [SMALL_STATE(164)] = 1531,
  [SMALL_STATE(165)] = 1538,
  [SMALL_STATE(166)] = 1545,
  [SMALL_STATE(167)] = 1552,
  [SMALL_STATE(168)] = 1559,
  [SMALL_STATE(169)] = 1566,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(119),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(149),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(163),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(164),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(166),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref, 3, 0, 5),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_behaviour_implementation, 7, 0, 4),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace_decl, 4, 0, 2),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_observation_provider, 7, 0, 4),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_observation_policy_repeat1, 2, 0, 0), SHIFT_REPEAT(163),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_observation_policy_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_observation_policy, 10, 0, 8),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_observation_policy, 9, 0, 7),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_observation_policy, 12, 0, 12),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_observation_policy, 13, 0, 14),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 2, 0, 1),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_execution, 21, 0, 25),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_execution, 22, 0, 25),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_execution, 22, 0, 27),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_execution, 23, 0, 27),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fqn, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fqn, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fqn_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fqn_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_observation, 10, 0, 18),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_observation, 7, 0, 15),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(158),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_length_unit, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_distance_value, 2, 0, 21),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(155),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(162),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(165),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scenario_execution_repeat1, 2, 0, 26), SHIFT_REPEAT(50),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scenario_execution_repeat1, 2, 0, 26),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(169),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scenario_execution_repeat1, 2, 0, 24),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simulation_entity_state_provider, 8, 0, 13),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ros_bhv_action, 4, 0, 6),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_horizon_seconds, 2, 0, 9),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ns_header, 5, 0, 3),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ros_trinary_topic, 4, 0, 10),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ros_topic_provider, 7, 0, 11),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(156),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_py_module_attr, 10, 0, 16),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(161),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(160),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_linear_distance_observation, 9, 0, 17),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_distance_constraint, 3, 0, 19),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_distance_constraint, 3, 0, 20),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_distance_constraint, 5, 0, 22),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_distance_constraint, 6, 0, 23),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [351] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bddx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_name,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
